{
 "title": "CE AWS Account Usage Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "account_owner", "label": "Owner", "query": "label_values(owner)" },
   {
    "name": "account_id",
    "label": "Account ID",
    "query": "aws_account_monthly_budget{owner=\"$account_owner\"}"
   },
   { "name": "year", "label": "Year", "query": "label_values(year)" },
   { "name": "month", "label": "Month", "query": "label_values(month)" },
   { "name": "discount", "label": "Discount(%)", "query": "0,5,10,15,20,25,30" }
  ]
 },
 "panels": [
  { "title": "AWS Account Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 }, "content": "### Account Name" },
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 3, "y": 1 }, "content": "### Month to date Spend" },
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 7, "y": 1 }, "content": "### Month Projected Spend" },
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 11, "y": 1 }, "content": "### Allocated Budget" },
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 15, "y": 1 }, "content": "### Percentage spend %" },
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 19, "y": 1 }, "content": "### Projected spend %" },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "repeat": "account_id",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "aws_account_monthly_budget{account_id=~'$account_id', year='$year', month='$month'}",
     "legendFormat": "{{account_name}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 3 },
   "repeat": "account_id",
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ce_aws_account_monthly_spend{account_id='$account_id', year='$year', month='$month'}) by (account_id) - (sum(ce_aws_account_monthly_spend{account_id='$account_id',year='$year', month='$month'}) by (account_id)/100 * $discount)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 3 },
   "repeat": "account_id",
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ce_aws_account_monthly_forecast{account_id='$account_id', year='$year', month='$month'}) by (account_id) - (sum(ce_aws_account_monthly_forecast{account_id='$account_id', year='$year', month='$month'}) by (account_id)/100 * $discount)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 3 },
   "repeat": "account_id",
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aws_account_monthly_budget{account_id='$account_id', year='$year', month='$month'}) by (account_id, month, year)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 3 },
   "repeat": "account_id",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(ce_aws_account_monthly_spend{account_id='$account_id',year='$year', month='$month' }) by (account_id)  - (sum(ce_aws_account_monthly_spend{account_id='$account_id',year='$year', month='$month'}) by (account_id)/100 * $discount)) / sum(aws_account_monthly_budget{account_id='$account_id',year='$year', month='$month'}) by (account_id)) * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 3 },
   "repeat": "account_id",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(ce_aws_account_monthly_forecast{account_id='$account_id',year='$year', month='$month' }) by (account_id)  - (sum(ce_aws_account_monthly_forecast{account_id='$account_id',year='$year', month='$month'}) by (account_id)/100 * $discount)) / sum(aws_account_monthly_budget{account_id='$account_id',year='$year', month='$month'}) by (account_id)) * 100"
    }
   ]
  },
  { "title": "AWS Service Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "Account" },
  {
   "title": "AWS Service Current Daily Spend",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Dollar($)" }
   ],
   "targets": [
    {
     "expr": "sum(ce_aws_service_daily_spend{account_id=~'$account_id', month='$month', year='$year'}) by (aws_service, account_id)  -\n(sum(ce_aws_service_daily_spend{account_id=~'$account_id', year='$year', month='$month'}) by (aws_service, account_id)/100 * $discount)",
     "legendFormat": "{{aws_service}}"
    }
   ]
  },
  {
   "title": "AWS Service Monthly Cost Spend",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Dollar($)" }
   ],
   "targets": [
    {
     "expr": "sum(ce_aws_service_monthly_spend{account_id=~'$account_id', month='$month', year='$year'}) by (aws_service, account_id) - (sum(ce_aws_service_monthly_spend{account_id=~'$account_id', year='$year', month='$month'}) by (aws_service, account_id)/100 * $discount)",
     "legendFormat": "{{aws_service}}"
    }
   ]
  },
  {
   "title": "AWS Service Monthly Projected Spend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Dollar($)" }
   ],
   "targets": [
    {
     "expr": "sum(ce_aws_service_monthly_forecast{account_id=~'$account_id', month='$month', year='$year'}) by (aws_service, account_id) - (sum(ce_aws_service_monthly_forecast{account_id=~'$account_id', year='$year', month='$month'}) by (aws_service, account_id)/100 * $discount)",
     "legendFormat": "{{aws_service}}"
    }
   ]
  }
 ]
}