variable "account_ids" {}
variable "parent" {}
variable "tags" {}
variable "costbuddy_output_bucket" {}
variable "cur_input_data_s3_path" {}
variable "cur_input_data_s3_daily_pattern" {}
variable "cur_input_data_s3_monthly_pattern" {}
variable "prometheus_push_gw_endpoint" {}
variable "prometheus_push_gw_port" {}
variable "out_bucket" {}
